### PR TITLE
Feature/support custom header camellia dashboard

### PR DESCRIPTION
**Pull request by tasszz2k**
- [x] `Camellia-redis-proxy`: Support custom header camellia dashboard from `application.yaml` configuration
- [x] Update documentation
- [ ] Update sample code `Camellia-dashboard-samples`

@caojiajun pls review for me, I will push code `Update sample code Camellia-dashboard-samples` later

### CODE REVIEW

**Comment by caojiajun** [comment]
api should forward compatibility

such as 'CamelliaApiUtil#init(String)', and constructor of CamelliaHBaseTemplate/CamelliaRedisTemplate, some method missing in your PR

**Comment by tasszz2k** [comment]
Would you suggest a way to check methods which missing the parameter? 
Seems IDEA doesn't warn that.

**Comment by caojiajun** [comment]
I mean only adding new api, not modifying existing api

**Comment by tasszz2k** [comment]
It means `CamelliaApiUtil` class should be here?

```java
public class CamelliaApiUtil {

    public static CamelliaApi init(String url, Map<String, String> headerMap) {
        return init(url, 10000, 60000, headerMap);
    }

    public static CamelliaApi init(String url, int connectTimeoutMillis, int readTimeoutMillis) {
        return init(url, connectTimeoutMillis, readTimeoutMillis, null);
    }

    public static CamelliaApi init(String url, int connectTimeoutMillis, int readTimeoutMillis, Map<String, String> headerMap) {
        return Feign.builder()
                .encoder(new JacksonEncoder())
                .decoder(new JacksonDecoder())
                .requestInterceptor(template -> {
                    if (CamelliaApiEnv.source != null) {
                        template.header(CamelliaApiEnv.REQUEST_SOURCE, CamelliaApiEnv.source);
                    }
                    if (headerMap != null && !headerMap.isEmpty()) {
                        for (Map.Entry<String, String> entry : headerMap.entrySet()) {
                            template.header(entry.getKey(), entry.getValue());
                        }
                    }
                })
                .options(new Request.Options(connectTimeoutMillis, readTimeoutMillis))
                .target(CamelliaApi.class, url);
    }
}

```

**Comment by caojiajun** [comment]
like this:

`public class CamelliaApiUtil {

	public static CamelliaApi init(String url) {
		return init(url, null);
	}

    public static CamelliaApi init(String url, Map<String, String> headerMap) {
        return init(url, 10000, 60000, headerMap);
    }

    public static CamelliaApi init(String url, int connectTimeoutMillis, int readTimeoutMillis) {
        return init(url, connectTimeoutMillis, readTimeoutMillis, null);
    }

    public static CamelliaApi init(String url, int connectTimeoutMillis, int readTimeoutMillis, Map<String, String> headerMap) {
        return Feign.builder()
                .encoder(new JacksonEncoder())
                .decoder(new JacksonDecoder())
                .requestInterceptor(template -> {
                    if (CamelliaApiEnv.source != null) {
                        template.header(CamelliaApiEnv.REQUEST_SOURCE, CamelliaApiEnv.source);
                    }
                    if (headerMap != null && !headerMap.isEmpty()) {
                        for (Map.Entry<String, String> entry : headerMap.entrySet()) {
                            template.header(entry.getKey(), entry.getValue());
                        }
                    }
                })
                .options(new Request.Options(connectTimeoutMillis, readTimeoutMillis))
                .target(CamelliaApi.class, url);
    }
}`

**Comment by tasszz2k** [comment]
Ex: `CamelliaHBaseTemplate` class, we have a constructor:
We will write a new constructor:
```java
    public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
                                 boolean monitorEnable, long checkIntervalMillis,
                                 int connectTimeoutMillis, int readTimeoutMillis, Map<String, String> headerMap) {
        this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis, headerMap), bid, bgroup, monitorEnable, checkIntervalMillis);
    }
```
from old constructor:
```java
    public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
                                 boolean monitorEnable, long checkIntervalMillis,
                                 int connectTimeoutMillis, int readTimeoutMillis) {
        this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis), bid, bgroup, monitorEnable, checkIntervalMillis);
    }
```
Should we modify it or keep the original? like this:
```java
    public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
                                 boolean monitorEnable, long checkIntervalMillis,
                                 int connectTimeoutMillis, int readTimeoutMillis) {
        this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis, null), bid, bgroup, monitorEnable, checkIntervalMillis);
    }
```

**Comment by tasszz2k** [comment]
Modified:
- [ ] CamelliaHBaseTemplate
- [ ] CamelliaTranspondProperties
- [ ] CamelliaRedisTemplate
- [ ] CamelliaRedisTemplateManager

**Comment by caojiajun** [comment]
> Ex: `CamelliaHBaseTemplate` class, we have a constructor: We will write a new constructor:
> 
> ```java
>     public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
>                                  boolean monitorEnable, long checkIntervalMillis,
>                                  int connectTimeoutMillis, int readTimeoutMillis, Map<String, String> headerMap) {
>         this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis, headerMap), bid, bgroup, monitorEnable, checkIntervalMillis);
>     }
> ```
> 
> from old constructor:
> 
> ```java
>     public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
>                                  boolean monitorEnable, long checkIntervalMillis,
>                                  int connectTimeoutMillis, int readTimeoutMillis) {
>         this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis), bid, bgroup, monitorEnable, checkIntervalMillis);
>     }
> ```
> 
> Should we modify it or keep the original? like this:
> 
> ```java
>     public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
>                                  boolean monitorEnable, long checkIntervalMillis,
>                                  int connectTimeoutMillis, int readTimeoutMillis) {
>         this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis, null), bid, bgroup, monitorEnable, checkIntervalMillis);
>     }
> ```



> Ex: `CamelliaHBaseTemplate` class, we have a constructor: We will write a new constructor:
> 
> ```java
>     public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
>                                  boolean monitorEnable, long checkIntervalMillis,
>                                  int connectTimeoutMillis, int readTimeoutMillis, Map<String, String> headerMap) {
>         this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis, headerMap), bid, bgroup, monitorEnable, checkIntervalMillis);
>     }
> ```
> 
> from old constructor:
> 
> ```java
>     public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
>                                  boolean monitorEnable, long checkIntervalMillis,
>                                  int connectTimeoutMillis, int readTimeoutMillis) {
>         this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis), bid, bgroup, monitorEnable, checkIntervalMillis);
>     }
> ```
> 
> Should we modify it or keep the original? like this:
> 
> ```java
>     public CamelliaHBaseTemplate(CamelliaHBaseEnv env, String url, long bid, String bgroup,
>                                  boolean monitorEnable, long checkIntervalMillis,
>                                  int connectTimeoutMillis, int readTimeoutMillis) {
>         this(env, CamelliaApiUtil.init(url, connectTimeoutMillis, readTimeoutMillis, null), bid, bgroup, monitorEnable, checkIntervalMillis);
>     }
> ```

old constructor should keep the original

**Comment by tasszz2k** [comment]
[dc5fe76](https://github.com/netease-im/camellia/pull/50/commits/dc5fe76ab6c01ac9399df9e9b1c4cd0749e53b19)
pls review it for me

> Modified:
> 
> * [x]  CamelliaApiUtil
> * [x]  CamelliaHBaseTemplate
> * [x]  CamelliaTranspondProperties
> * [x]  CamelliaRedisTemplate
> * [x]  CamelliaRedisTemplateManager

**Comment by caojiajun** [comment]
seems no problem

**Comment by tasszz2k** [comment]
> seems no problem

thank you, bro 👍 
I will push code `Update sample code Camellia-dashboard-samples with authentication optional` later

**Comment by caojiajun** [comment]
> > seems no problem
> 
> thank you, bro 👍 I will push code `Update sample code Camellia-dashboard-samples with authentication optional` later

thank you very much~

**Pull request merged**
