### PR TITLE
Feature/support custom header camellia dashboard

### PR DESCRIPTION
**Pull request by tasszz2k**
- [x] Update sample code `Camellia-dashboard-samples`
- [x] Add documentation

@caojiajun pls review for me

### CODE REVIEW

**Comment by caojiajun** [comment]
could you remove lombok dependency in camellia-dashboard-samples?

**Comment by tasszz2k** [comment]
> could you remove lombok dependency in camellia-dashboard-samples?

ok, let me do it

**Comment by tasszz2k** [comment]
[bbe5408](https://github.com/netease-im/camellia/pull/51/commits/bbe540899cbf8357b31bda170dc9dac50c347d00) 
@caojiajun pls review it for me

**Comment by caojiajun** [comment]
This branch has conflicts that must be resolved 

here：camellia-samples/camellia-dashboard-samples/pom.xml

**Comment by caojiajun** [comment]
you can use the web editor of github in current http page

**Comment by tasszz2k** [comment]
> you can use the web editor of github in current http page

ok, it done

**Comment by tasszz2k** [comment]
thank you very much 
:"D

**Pull request merged**
