### PR TITLE
Feature: Dynamic update ip check proxy

### PR DESCRIPTION
**Pull request by tasszz2k**
This feature provides a `Dynamic IP Checker Plugin` - A plugin for IP black and white list restrictions on clients accessing the proxy.
It will read configurations via `camellia-dashboard` like how we fetch data from that. 
We will store these configurations in the database instead of a file.

----

**Camellia-dashboard**:
image

**Camellia-redis-proxy**:
- Fetch IP checker data from API: [GET](http://localhost:8080/swagger-ui.html#!/api%E6%8E%A5%E5%8F%A3/getIpCheckerListUsingGET) [/camellia/api/permissions/ip-checkers](http://localhost:8080/swagger-ui.html#!/api%E6%8E%A5%E5%8F%A3/getIpCheckerListUsingGET) 
- Proxy plugin update interval confg by key in `camellia-redis-proxy.properties`: `proxy.plugin.update.interval.seconds`
---
I try testing with several scenarios and it works! : D 

**Checklist:** 

- [x] **Camellia-dashboard**: Provide API support to create/update/delete IP Checker configurations
- [x] **Camellia-dashboard**: Caching IP checker data
- [x] **Camellia-redis-proxy**:  Apply `dynamicIpCheckerPlugin` plugin
- [x] **Documentation**: Add documentation and guideline 

**Need to confirm/fix:**
- [ ] I don't know how to get the `apiService` from the `ProxyBeanFactory`. So I try getting it from `AsyncCamelliaRedisTemplateChooser`. I think it's not a good idea to get it from `AsyncCamelliaRedisTemplateChooser`. But this is the only way I can do it.

@caojiajun pls help me review it. 👍

### CODE REVIEW

**Comment by tasszz2k** [comment]
All items on the checklist have been done. I add new documentation at [docs/redis-proxy/plugin/dynamic-ip-checker.md](docs/redis-proxy/plugin/dynamic-ip-checker.md)
pls help me review it, @caojiajun 👍

**Comment by caojiajun** [comment]
```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AssertionFailure: AttributeConverter class [class com.netease.nim.camellia.dashboard.util.StringCollectionConverter] registered multiple times
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1087)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
        at com.netease.nim.camellia.dashboard.Application.main(Application.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.hibernate.AssertionFailure: AttributeConverter class [class com.netease.nim.camellia.dashboard.util.StringCollectionConverter] registered multiple times

```

**Comment by caojiajun** [comment]
pls check this error

**Comment by caojiajun** [comment]
errors missing after remove the annotation 
https://github.com/netease-im/camellia/commit/880da96b46dc555460d22dd2817535747adddb37

**Comment by tasszz2k** [comment]
> errors missing after remove the annotation [880da96](https://github.com/netease-im/camellia/commit/880da96b46dc555460d22dd2817535747adddb37)

please do not remove the `@Converter` annotation
That supports converting `varchar` SQL type <=> `List` Collection Java
https://docs.oracle.com/javaee/7/api/javax/persistence/Converter.html

**Comment by tasszz2k** [comment]
image

IntelliJ IDEA warn that, pls recheck

**Comment by caojiajun** [comment]
without the annotation, 'StringCollectionConverter' works well

**Comment by tasszz2k** [comment]
> without the annotation, 'StringCollectionConverter' works well

But, why do we need to remove this annotation?
It is not recommended.

**Comment by caojiajun** [comment]
> ```java
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AssertionFailure: AttributeConverter class [class com.netease.nim.camellia.dashboard.util.StringCollectionConverter] registered multiple times
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
>         at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1087)
>         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
>         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
>         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
>         at com.netease.nim.camellia.dashboard.Application.main(Application.java:17)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
>         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
> Caused by: org.hibernate.AssertionFailure: AttributeConverter class [class com.netease.nim.camellia.dashboard.util.StringCollectionConverter] registered multiple times
> ```

because this error occur in our dev environment

**Comment by tasszz2k** [comment]
oh, sorry 
 It still works in my dev environment.

**Comment by caojiajun** [comment]
the error seems occur occasionally

**Pull request merged**
