### PR TITLE
Feature: support prometheus/grafana for camellia-redis-proxy

### PR DESCRIPTION
**Pull request by tasszz2k**
## TODO:

- [x] Implement `StatsPrometheusConverter.converter(Stats)` method 
- [x]  big.key.stats
- [x]  hot.key.stats
- [x]  hot.key.cache.stats
- [x]  slow.command.stats
- [x]  Expose a new endpoint `/prometheus`
- [x] Test
- [x] Visualize on Grafana
## What?
- Support Prometheus/Grafana for camellia-redis-proxy
- See ticket https://github.com/netease-im/camellia/issues/66

## Why?
- Support Observable and tracing

## How?
- Implement `StatsPrometheusConverter.converter(Stats)` method
- Expose a new endpoint `/prometheus`
## Testing?
- Not yet
- result:
```
# HELP redis_proxy_connect_count Redis Proxy Connect Count
# TYPE redis_proxy_connect_count gauge
redis_proxy_connect_count 2
# HELP redis_proxy_total Redis Proxy Total
# TYPE redis_proxy_total counter
redis_proxy_total{type="all",} 9
redis_proxy_total{type="read",} 7
redis_proxy_total{type="write",} 2
# HELP redis_proxy_total_command Redis Proxy Total Command
# TYPE redis_proxy_total_command counter
redis_proxy_total_command{command="keys",} 1
redis_proxy_total_command{command="client",} 2
redis_proxy_total_command{command="mget",} 2
redis_proxy_total_command{command="command",} 4
# HELP redis_proxy_bid_bgroup Redis Proxy Bid Bgroup
# TYPE redis_proxy_bid_bgroup gauge
redis_proxy_bid_bgroup{bid="3",bgroup="tass",} 2
redis_proxy_bid_bgroup{bid="default",bgroup="default",} 6
redis_proxy_bid_bgroup{bid="907",bgroup="tass",} 1
# HELP redis_proxy_detail Redis Proxy Detail
# TYPE redis_proxy_detail counter
redis_proxy_detail{bid="default",bgroup="default",command="command",} 4
redis_proxy_detail{bid="default",bgroup="default",command="client",} 2
redis_proxy_detail{bid="3",bgroup="tass",command="mget",} 1
redis_proxy_detail{bid="907",bgroup="tass",command="mget",} 1
redis_proxy_detail{bid="3",bgroup="tass",command="keys",} 1
# HELP redis_proxy_fail Redis Proxy Fail
# TYPE redis_proxy_fail counter
redis_proxy_fail{reason="Not Available",} 4
redis_proxy_fail{reason="Not Support",} 1
# HELP redis_proxy_spend_stats Redis Proxy Spend Stats
# TYPE redis_proxy_spend_stats summary
redis_proxy_spend_stats_sum{command="keys",} 75.596958
redis_proxy_spend_stats_count{command="keys",} 1
redis_proxy_spend_stats{command="keys",quantile="0.5"} 0.000000
redis_proxy_spend_stats{command="keys",quantile="0.75"} 0.000000
redis_proxy_spend_stats{command="keys",quantile="0.90"} 0.000000
redis_proxy_spend_stats{command="keys",quantile="0.95"} 0.000000
redis_proxy_spend_stats{command="keys",quantile="0.99"} 0.000000
redis_proxy_spend_stats{command="keys",quantile="0.999"} 0.000000
redis_proxy_spend_stats{command="keys",quantile="1"} 75.590000
redis_proxy_spend_stats_sum{command="client",} 24.386459
redis_proxy_spend_stats_count{command="client",} 2
redis_proxy_spend_stats{command="client",quantile="0.5"} 1.600000
redis_proxy_spend_stats{command="client",quantile="0.75"} 1.600000
redis_proxy_spend_stats{command="client",quantile="0.90"} 1.600000
redis_proxy_spend_stats{command="client",quantile="0.95"} 1.600000
redis_proxy_spend_stats{command="client",quantile="0.99"} 1.600000
redis_proxy_spend_stats{command="client",quantile="0.999"} 1.600000
redis_proxy_spend_stats{command="client",quantile="1"} 22.780000
redis_proxy_spend_stats_sum{command="mget",} 356.385126
redis_proxy_spend_stats_count{command="mget",} 2
redis_proxy_spend_stats{command="mget",quantile="0.5"} 43.900000
redis_proxy_spend_stats{command="mget",quantile="0.75"} 43.900000
redis_proxy_spend_stats{command="mget",quantile="0.90"} 43.900000
redis_proxy_spend_stats{command="mget",quantile="0.95"} 43.900000
redis_proxy_spend_stats{command="mget",quantile="0.99"} 43.900000
redis_proxy_spend_stats{command="mget",quantile="0.999"} 43.900000
redis_proxy_spend_stats{command="mget",quantile="1"} 312.620000
redis_proxy_spend_stats_sum{command="command",} 19.682250
redis_proxy_spend_stats_count{command="command",} 4
redis_proxy_spend_stats{command="command",quantile="0.5"} 0.020000
redis_proxy_spend_stats{command="command",quantile="0.75"} 0.030000
redis_proxy_spend_stats{command="command",quantile="0.90"} 0.030000
redis_proxy_spend_stats{command="command",quantile="0.95"} 0.030000
redis_proxy_spend_stats{command="command",quantile="0.99"} 0.030000
redis_proxy_spend_stats{command="command",quantile="0.999"} 0.030000
redis_proxy_spend_stats{command="command",quantile="1"} 19.600000
# HELP redis_proxy_bid_bgroup_spend_stats Redis Proxy Bid Bgroup Spend Stats
# TYPE redis_proxy_bid_bgroup_spend_stats summary
redis_proxy_bid_bgroup_spend_stats_sum{bid="default",bgroup="default",command="command",} 19.682250
redis_proxy_bid_bgroup_spend_stats_count{bid="default",bgroup="default",command="command",} 4
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="command",quantile="0.5"} 0.020000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="command",quantile="0.75"} 0.030000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="command",quantile="0.90"} 0.030000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="command",quantile="0.95"} 0.030000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="command",quantile="0.99"} 0.030000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="command",quantile="0.999"} 0.030000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="command",quantile="1"} 19.600000
redis_proxy_bid_bgroup_spend_stats_sum{bid="default",bgroup="default",command="client",} 24.386459
redis_proxy_bid_bgroup_spend_stats_count{bid="default",bgroup="default",command="client",} 2
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="client",quantile="0.5"} 1.600000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="client",quantile="0.75"} 1.600000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="client",quantile="0.90"} 1.600000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="client",quantile="0.95"} 1.600000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="client",quantile="0.99"} 1.600000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="client",quantile="0.999"} 1.600000
redis_proxy_bid_bgroup_spend_stats{bid="default",bgroup="default",command="client",quantile="1"} 22.780000
redis_proxy_bid_bgroup_spend_stats_sum{bid="3",bgroup="tass",command="mget",} 43.761209
redis_proxy_bid_bgroup_spend_stats_count{bid="3",bgroup="tass",command="mget",} 1
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="mget",quantile="0.5"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="mget",quantile="0.75"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="mget",quantile="0.90"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="mget",quantile="0.95"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="mget",quantile="0.99"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="mget",quantile="0.999"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="mget",quantile="1"} 43.760000
redis_proxy_bid_bgroup_spend_stats_sum{bid="907",bgroup="tass",command="mget",} 312.623917
redis_proxy_bid_bgroup_spend_stats_count{bid="907",bgroup="tass",command="mget",} 1
redis_proxy_bid_bgroup_spend_stats{bid="907",bgroup="tass",command="mget",quantile="0.5"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="907",bgroup="tass",command="mget",quantile="0.75"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="907",bgroup="tass",command="mget",quantile="0.90"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="907",bgroup="tass",command="mget",quantile="0.95"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="907",bgroup="tass",command="mget",quantile="0.99"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="907",bgroup="tass",command="mget",quantile="0.999"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="907",bgroup="tass",command="mget",quantile="1"} 312.620000
redis_proxy_bid_bgroup_spend_stats_sum{bid="3",bgroup="tass",command="keys",} 75.596958
redis_proxy_bid_bgroup_spend_stats_count{bid="3",bgroup="tass",command="keys",} 1
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="keys",quantile="0.5"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="keys",quantile="0.75"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="keys",quantile="0.90"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="keys",quantile="0.95"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="keys",quantile="0.99"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="keys",quantile="0.999"} 0.000000
redis_proxy_bid_bgroup_spend_stats{bid="3",bgroup="tass",command="keys",quantile="1"} 75.590000
# HELP redis_proxy_resource_stats Redis Proxy Resource Stats
# TYPE redis_proxy_resource_stats counter
redis_proxy_resource_stats{"resource"="redis://@127.0.0.1:6377",} 1
redis_proxy_resource_stats{"resource"="redis://@127.0.0.1:6379",} 1
# HELP redis_proxy_resource_command_stats Redis Proxy Resource Command Stats
# TYPE redis_proxy_resource_command_stats counter
redis_proxy_resource_command_stats{"resource"="redis://@127.0.0.1:6379",command="mget",} 1
redis_proxy_resource_command_stats{"resource"="redis://@127.0.0.1:6377",command="mget",} 1
# HELP redis_proxy_bid_bgroup_resource_command_stats Redis Proxy Bid Bgroup Resource Command Stats
# TYPE redis_proxy_bid_bgroup_resource_command_stats counter
redis_proxy_bid_bgroup_resource_command_stats{"bid"="3",bgroup="tass",resource="redis://@127.0.0.1:6379",command="mget",} 1
redis_proxy_bid_bgroup_resource_command_stats{"bid"="907",bgroup="tass",resource="redis://@127.0.0.1:6377",command="mget",} 1
# HELP redis_proxy_redis_connect_stats Redis Proxy Redis Connect Stats
# TYPE redis_proxy_redis_connect_stats gauge
redis_proxy_redis_connect_stats{redis_addr="@127.0.0.1:6377",} 1
redis_proxy_redis_connect_stats{redis_addr="@127.0.0.1:6379",} 2
# HELP redis_proxy_upstream_redis_spend_stats Redis Proxy Upstream Redis Spend Stats
# TYPE redis_proxy_upstream_redis_spend_stats summary
redis_proxy_upstream_redis_spend_stats_sum{redis_addr="@127.0.0.1:6379",} 9.256542
redis_proxy_upstream_redis_spend_stats_count{redis_addr="@127.0.0.1:6379",} 3
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6379",quantile="0.5"} 1.040000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6379",quantile="0.75"} 2.900000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6379",quantile="0.9"} 2.900000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6379",quantile="0.95"} 2.900000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6379",quantile="0.99"} 2.900000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6379",quantile="0.999"} 2.900000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6379",quantile="1"} 5.290000
redis_proxy_upstream_redis_spend_stats_sum{redis_addr="@127.0.0.1:6377",} 36.825708
redis_proxy_upstream_redis_spend_stats_count{redis_addr="@127.0.0.1:6377",} 2
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6377",quantile="0.5"} 16.400000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6377",quantile="0.75"} 16.400000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6377",quantile="0.9"} 16.400000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6377",quantile="0.95"} 16.400000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6377",quantile="0.99"} 16.400000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6377",quantile="0.999"} 16.400000
redis_proxy_upstream_redis_spend_stats{redis_addr="@127.0.0.1:6377",quantile="1"} 20.540000
1
```
- @caojiajun, pls help me review it.

### CODE REVIEW

**Comment by tasszz2k** [comment]
@caojiajun  If you have time, please help me review it. 

Thank you.

**Comment by caojiajun** [comment]
the code seems no problems.
i will merge pull request when all sub-tasks done.

**Comment by tasszz2k** [comment]
In the commit https://github.com/netease-im/camellia/pull/84/commits/d97c6ff789f68d519716fd3f16b2e84c41ae0ebc

I don't push all labels of plugins because it leads to an extremely big size of response, so I counted by `each Key`.

**Comment by caojiajun** [comment]
> 

it's appropriate

**Comment by phuc1998** [comment]
Dear @caojiajun, can you release soon when this PR merged?

**Comment by caojiajun** [comment]
> Dear @caojiajun, can you release soon when this PR merged?

no problem.

when the sub-task `Visualize on Grafana` done, PR will merged, and 1.1.11 will release.

**Comment by tasszz2k** [comment]
Is camellia redis proxy not expose the number of connections per tenant (bid/bgroup)?

I found only the total connections and the number of connections per redis resource

**Comment by caojiajun** [comment]
> Is camellia redis proxy not expose the number of connections per tenant (bid/bgroup)?
> 
> I found only the total connections and the number of connections per redis resource

we can expose it by `ChannelMonitor.java`

**Comment by tasszz2k** [comment]
Ok, it done
image

**Comment by tasszz2k** [comment]
Ok, it done
image

**Comment by caojiajun** [comment]
> Is camellia redis proxy not expose the number of connections per tenant (bid/bgroup)?
> 
> I found only the total connections and the number of connections per redis resource

this commit:
https://github.com/netease-im/camellia/commit/51df945d1534b6544bc21214801dd93ec656150c

**Comment by caojiajun** [comment]
> Ok, it done
> image

great！
maybe we need some documents about the grafana dashboard.

**Comment by tasszz2k** [comment]
> great！ maybe we need some documents about the grafana dashboard.

Hmm, what is it?

**Comment by tasszz2k** [comment]
I hope you can release the next version soon to fix the issue https://github.com/netease-im/camellia/issues/82
We can add more docs later.
: D

**Comment by caojiajun** [comment]
@tasszz2k I have some question abount `/prometheus`, pls help me.
`redis_proxy_total_command` this metrics use `counter`
and grafana use `sum(rate(redis_proxy_total_command{instance=~\"$Instance\"}[1m])) by (command)`, if current minute is `100`, next minute is `50`, the `rate` function seems incorrect?

**Comment by tasszz2k** [comment]
> @tasszz2k I have some question abount `/prometheus`, pls help me. `redis_proxy_total_command` this metrics use `counter` and grafana use `sum(rate(redis_proxy_total_command{instance=~\"$Instance\"}[1m])) by (command)`, if current minute is `100`, next minute is `50`, the `rate` function seems incorrect?

okay, let me check

**Pull request merged**
